// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProblemReport.Data;

#nullable disable

namespace ProblemReport.Data.Migrations
{
    [DbContext(typeof(ProblemReportContext))]
    [Migration("20250719141607_SeedReports")]
    partial class SeedReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProblemReport.Entities.Entity.Report", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImageType")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("SubSystem")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = "0242b3bb-ed95-4c34-a2b8-5cfe9cc20ffe",
                            Date = new DateTime(2025, 7, 19, 16, 16, 6, 844, DateTimeKind.Local).AddTicks(466),
                            ImagePath = "../Assets/UploadedImages/not_found.png",
                            ImageType = "png",
                            SubSystem = 2,
                            Text = "Nem talható az oldal."
                        },
                        new
                        {
                            Id = "2badc1fd-4ea7-42b2-bd14-9a8594641f65",
                            Date = new DateTime(2025, 7, 18, 16, 16, 6, 844, DateTimeKind.Local).AddTicks(473),
                            ImagePath = "../Assets/UploadedImages/server_error.jpg",
                            ImageType = "jpg",
                            SubSystem = 3,
                            Text = "A szerver hibát jelez"
                        },
                        new
                        {
                            Id = "342219dd-992f-41f0-acfc-088936a7059f",
                            Date = new DateTime(2025, 7, 17, 16, 16, 6, 844, DateTimeKind.Local).AddTicks(492),
                            ImagePath = "../Assets/UploadedImages/timeout.jpg",
                            ImageType = "jpg",
                            SubSystem = 4,
                            Text = "Nem tölti be az oldalt."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
