// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProblemReport.Data;

#nullable disable

namespace ProblemReport.Data.Migrations
{
    [DbContext(typeof(ProblemReportContext))]
    [Migration("20250719184742_ReportStatus")]
    partial class ReportStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("ProblemReport.Entities.Entity.Report", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageType")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = "12c2cfb1-b248-4bae-b2a9-9ec3070f6019",
                            Date = new DateTime(2025, 7, 19, 20, 47, 41, 218, DateTimeKind.Local).AddTicks(4903),
                            ImagePath = "../Assets/UploadedImages/not_found.png",
                            ImageType = "png",
                            Status = "Open",
                            SubSystem = 2,
                            Text = "Nem talható az oldal."
                        },
                        new
                        {
                            Id = "598cfd0f-99ed-4abd-b8ec-015864722c55",
                            Date = new DateTime(2025, 7, 18, 20, 47, 41, 218, DateTimeKind.Local).AddTicks(4909),
                            ImagePath = "../Assets/UploadedImages/server_error.jpg",
                            ImageType = "jpg",
                            Status = "Open",
                            SubSystem = 3,
                            Text = "A szerver hibát jelez"
                        },
                        new
                        {
                            Id = "4b4cb4f6-5dcf-441e-8dd0-ec0e3f6252fd",
                            Date = new DateTime(2025, 7, 17, 20, 47, 41, 218, DateTimeKind.Local).AddTicks(4916),
                            ImagePath = "../Assets/UploadedImages/timeout.jpg",
                            ImageType = "jpg",
                            Status = "Open",
                            SubSystem = 4,
                            Text = "Nem tölti be az oldalt."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
