// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProblemReport.Data;

#nullable disable

namespace ProblemReport.Data.Migrations
{
    [DbContext(typeof(ProblemReportContext))]
    partial class ProblemReportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("ProblemReport.Entities.Entity.Report", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageType")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("SubSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = "4e1bfd16-cb16-4c62-856d-2260e66a057a",
                            Date = new DateTime(2025, 7, 19, 18, 15, 45, 63, DateTimeKind.Local).AddTicks(980),
                            ImagePath = "../Assets/UploadedImages/not_found.png",
                            ImageType = "png",
                            SubSystem = 2,
                            Text = "Nem talható az oldal."
                        },
                        new
                        {
                            Id = "085f9ae6-f643-4df1-9338-4270b8960de1",
                            Date = new DateTime(2025, 7, 18, 18, 15, 45, 63, DateTimeKind.Local).AddTicks(994),
                            ImagePath = "../Assets/UploadedImages/server_error.jpg",
                            ImageType = "jpg",
                            SubSystem = 3,
                            Text = "A szerver hibát jelez"
                        },
                        new
                        {
                            Id = "ebf80d29-7870-4ecc-a46f-75219927dfaa",
                            Date = new DateTime(2025, 7, 17, 18, 15, 45, 63, DateTimeKind.Local).AddTicks(1001),
                            ImagePath = "../Assets/UploadedImages/timeout.jpg",
                            ImageType = "jpg",
                            SubSystem = 4,
                            Text = "Nem tölti be az oldalt."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
